version: '3.8'
services:
  back:
    build: 
      context: ./back
      dockerfile: ../docker/back/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./back:/app
    depends_on: 
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - .dbdate:/var/lib/mysql
    ports: 
      - 3306:3306

  front:
    build: 
      context: ./front
      dockerfile: ../docker/front/Dockerfile
    restart: always
    volumes:
      - ./front:/usr/src/app:cached
    ports:
      - "3000:3000"